# Generated by Django 3.0.8 on 2020-07-31 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Class of room')),
                ('unique_color', models.CharField(blank=True, help_text='This should an HEX code for every unique class of room', max_length=35, unique=True)),
                ('max_room_no', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('condition', models.CharField(choices=[('bad', 'Bad'), ('good', 'Good')], default='good', max_length=20)),
                ('status', models.CharField(choices=[('occupied', 'Unavailable'), ('booked', 'Booked'), ('free', 'Available')], default='free', max_length=20)),
                ('date_issued', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='rooms.RoomCategory')),
            ],
        ),
    ]
